# Feature Extraction Settings
features:
  face:
    enabled: true
    similarity_threshold: 0.6
    min_face_size: 32
  llava:
    enabled: true
    api_endpoint: "https://api.llava.ai/v1/describe"
    min_person_height: 100  # pixels
    appearance_match_threshold: 0.8

# Re-identification Settings
reid:
  time_decay:
    tau: 300.0  # seconds
    min_weight: 0.1
  feature_matching:
    min_similarity: 0.8  # 80% similarity threshold for robust re-identification
    required_match_percentage: 0.8
  database:
    db_path: "reid_profiles.db"  # SQLite database path
    max_profiles: 1000
    cleanup_interval: 3600  # seconds
  track_timeout: 30  # seconds before considering a track truly lost

# Tracking Settings
tracker:
  byte_track:
    model_path: "yolov8n.pt"  # YOLOv8 model for person detection
    track_thresh: 0.5
    track_buffer: 30
    match_thresh: 0.8
    min_box_area: 100
    mot20: false
    iou_threshold: 0.7
    device: "auto"  # "cpu", "cuda", or "auto"

# Logging Settings
logging:
  level: "INFO"
  save_appearance_json: true
  output_dir: "logs"
  log_interval: 100  # frames

# Visualization Settings
visualization:
  show_track_ids: false  # Only show global IDs
  show_global_ids: true
  show_confidence: false
  box_thickness: 2  # Not used anymore (no bounding boxes)
  text_scale: 0.8  # Larger text for better visibility
  colors:
    - [255, 0, 0]    # Red
    - [0, 255, 0]    # Green
    - [0, 0, 255]    # Blue
    - [255, 255, 0]  # Yellow
    - [255, 0, 255]  # Magenta
    - [0, 255, 255]  # Cyan
    - [255, 165, 0]  # Orange
    - [128, 0, 128]  # Purple
    - [255, 192, 203] # Pink
    - [0, 128, 0]    # Dark Green 