# Feature Extraction Settings
features:
  face:
    enabled: true
    similarity_threshold: 0.6
    model_name: "buffalo_l"
  llava:
    enabled: true
    server_url: "http://localhost:11434"
    model_name: "llava"

# Re-identification Settings
reid:
  feature_matching:
    min_similarity: 0.8  # 80% similarity threshold for robust re-ID
    required_match_percentage: 0.8
  database:
    db_path: "reid_profiles.db"
    max_profiles: 1000
    cleanup_interval: 300  # seconds
  time_decay:
    tau: 86400  # 24 hours in seconds
    min_weight: 0.1

# Tracking Settings
tracker:
  byte_track:
    model_path: "yolov8n.pt"
    track_thresh: 0.5
    iou_threshold: 0.7
    device: "auto"  # auto, cpu, cuda
    min_box_area: 100

# Logging Settings
logging:
  level: "INFO"
  output_dir: "logs"
  log_interval: 100  # frames

# Visualization Settings
visualization:
  show_track_ids: false
  show_global_ids: true
  show_confidence: false
  text_scale: 0.8
  colors:
    - [255, 0, 0]     # Red
    - [0, 255, 0]     # Green
    - [0, 0, 255]     # Blue
    - [255, 255, 0]   # Yellow
    - [255, 0, 255]   # Magenta
    - [0, 255, 255]   # Cyan
    - [255, 128, 0]   # Orange
    - [128, 0, 255]   # Purple
  box_thickness: 2  # Not used anymore (no bounding boxes)
  text_scale: 0.8  # Larger text for better visibility
  colors:
    - [255, 0, 0]    # Red
    - [0, 255, 0]    # Green
    - [0, 0, 255]    # Blue
    - [255, 255, 0]  # Yellow
    - [255, 0, 255]  # Magenta
    - [0, 255, 255]  # Cyan
    - [255, 165, 0]  # Orange
    - [128, 0, 128]  # Purple
    - [255, 192, 203] # Pink
    - [0, 128, 0]    # Dark Green 